version: '2'
services:
  postgres:
    image: postgres
    # volumes:
    #     - ~/volumes/jhipster/todo_hipster/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
